New registration flow
scilus/registration_flow pull request #1
Opened 2021-06-02 19:17 UTC by ppoulin91

For each subject, register T1 to template, then apply transformation to all `.nii.gz` or `.trk` files

2021-06-14 14:52 UTC, arnaudbore reviewed
Great job, we should be ready to merge and release pretty soon !

2021-06-14 14:52 UTC, arnaudbore commented on nextflow.config
> +    Readme_Publish_Dir = "./results/Readme"
```suggestion
    Readme_Publish_Dir = "./results_registration/Readme"
```

2021-06-14 14:52 UTC, arnaudbore commented on USAGE
> +                                        |   ├── *t1.nii.gz
Check that you don't have multiple t1 within each folder check number of subject compare with number of t1s

2021-06-14 14:52 UTC, arnaudbore commented on README.md
> +See *USAGE* or run `nextflow run main.nf --help`
You should suggest to use registration_flow `release 1.0.0` with  with dockerhub scilus/scilus:1.1.0_registrationflow-1.0.0 :)

2021-06-14 14:52 UTC, arnaudbore commented on main.nf
> +        t1: it =~ "t1.nii.gz"
does it work if we call the t1 `sub-toto_t1.nii.gz` ?

2021-06-14 14:52 UTC, arnaudbore commented on main.nf
> +    error "Error ~ No subjects found. Please check the naming convention, your --input path or your BIDS folder."}
Not really a BIDS folder ;)

2021-06-14 14:52 UTC, arnaudbore commented on USAGE
> +Files should be compressed Nifti files (.nii.gz) or TRK tractograms (.trk)
can we be crazy and accept tck with t1 reference ?

2021-06-14 14:52 UTC, arnaudbore commented on USAGE
> +Files should be compressed Nifti files (.nii.gz) or TRK tractograms (.trk)
You could have a specific channel for tck files.

2021-06-14 14:52 UTC, arnaudbore commented on README.md
> +See *USAGE* or run `nextflow run main.nf --help`
I will push this tag

2021-06-14 14:57 UTC, arnaudbore commented on README.md
> +See *USAGE* or run `nextflow run main.nf --help`
Done -> scilus/scilus:1.1.0_registrationflow-1.0.0 exists

2021-06-14 14:59 UTC, GuillaumeTh requested changes

2021-06-14 14:59 UTC, GuillaumeTh commented on USAGE
> +===================
Match the length of your previous line with "=".

2021-06-14 14:59 UTC, GuillaumeTh commented on USAGE
> +AVAILABLE PROFILES (using -profile option (e.g. -profile use_cuda,fully_reproducible))
Remove use_cuda and fully_reprocducible and add macos as the example

2021-06-14 14:59 UTC, GuillaumeTh commented on main.nf
> +log.info "==================="
Match the length of your previous line with "=".

2021-06-14 14:59 UTC, GuillaumeTh commented on main.nf
> +    .into {template_for_registration; template_for_transformation_nii; template_for_transformation_trk}
If you don't want to have multiple channels for the same template, you can do something like: 

set sid, file(t1) from t1_for_registration
file(template) from template_for_registration.first()

2021-06-14 14:59 UTC, GuillaumeTh commented on main.nf
> +Channel
Not a comment but really cool !

2021-06-14 14:59 UTC, GuillaumeTh commented on main.nf
> +    error "Error ~ No subjects found. Please check the naming convention, your --input path or your BIDS folder."}
Please modify to remove BIDS

2021-06-14 14:59 UTC, GuillaumeTh commented on main.nf
> +    set sid, file(t1), file(template) from t1_and_template_for_registration
As I said previously you can modify this

2021-06-14 14:59 UTC, GuillaumeTh commented on main.nf
> +    set sid, file(transfo), file(nii), file(template) from nii_and_template_for_transformation
Same here you can have template in an other channel.

2021-06-14 14:59 UTC, GuillaumeTh commented on main.nf
> +    set sid, file(transfo), file(trk), file(template) from trk_and_template_for_transformation
Same here you can have template in an other channel.

2021-06-14 14:59 UTC, GuillaumeTh commented on nextflow.config
> +        processes = false
Remove extra space.

2021-06-14 15:02 UTC, ppoulin91 commented on USAGE
> +Files should be compressed Nifti files (.nii.gz) or TRK tractograms (.trk)
@GuillaumeTh  says no... I'll let you guys talk about it

2021-06-14 15:03 UTC, ppoulin91 commented on nextflow.config
> +    publishDir = {"./results/$sid/$task.process"}
Chat with @GuillaumeTh

2021-06-14 15:10 UTC, ppoulin91 commented on USAGE
> +                                        |   ├── *t1.nii.gz
After a chat with @GuillaumeTh , user should be responsible for this, I can push a PR in combine_flows to add my conversion script from TractoFlow

2021-06-14 17:01 UTC, ppoulin91 commented on main.nf
> +        t1: it =~ "t1.nii.gz"
Yes: `=~` matches the following regex anywhere in the string

2021-06-14 17:03 UTC, arnaudbore commented on README.md
> +[scilus/scilus:1.1.0_registrationflow-1.0.0](https://hub.docker.com/layers/scilus/scilus/1.1.0_registrationflow-1.0.0/images/sha256-1726d651667a964f7b0808b8383fac6a92c1c126c45a940da1d7ea5a1693bdb0)
You can just tell them to add this depending on docker or singularity

-with-docker scilus/scilus:1.1.0_registrationflow-1.0.0

or

dl: http://scil.usherbrooke.ca/en/containers_list/scilus-1.1.0_registrationflow-1.0.0.img 

-with-singularity /pathto/scilus-1.1.0_registrationflow-1.0.0.img

2021-06-14 17:49 UTC, ppoulin91 commented on USAGE
> +                                        |   ├── *t1.nii.gz
I added the validation check :)

2021-06-14 17:56 UTC, ppoulin91 commented
I have answered all comments here, please review again if everything is ok!

2021-06-14 18:18 UTC, arnaudbore approved these changes
minor comments LGTM !

2021-06-14 18:18 UTC, arnaudbore commented on README.md
> +Simply add the following to yout `nextflow run` command:
```suggestion
Simply add the following to your `nextflow run` command:
```

2021-06-14 18:18 UTC, arnaudbore commented on README.md
> +Prebuilt Docker images are available here:
get rid of these two lines

2021-06-14 18:18 UTC, arnaudbore commented on README.md
> +Prebuilt Docker images are available here:
now they have all information needed with docker and singularity we don't need to give the link to these singularity images

2021-06-15 18:10 UTC, GuillaumeTh approved these changes
LGTM ! :beers:

2021-06-15 18:13 UTC, merged